replicaCount: 1

image:
  repository: geekform-backend
  tag: v1
  pullPolicy: Never

service:
  type: NodePort
  port: 80

postgres:
  user: geekform
  password: geekformpw
  database: geekformdb
  storage: 1Gi
