apiVersion: v1
kind: Service
metadata:
  name: geekform-backend
spec:
  type: NodePort
  selector:
    app: geekform-backend
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
